"""
Pyww module variables for versioning and misc env keys
"""

VERSION = "0.0.1a0"
ENVIRON_DEBUG_KEY = "PYWB_DEBUG"
ENVIRON_LOG_DIR_KEY = "PYWB_LOG_DIR"
ENVIRON_DOCKER_CONTAINER_KEY = "AM_I_IN_A_DOCKER_CONTAINER"
